Repository googleforgames/open-saves, pull requests merged in 2021-08, with the labels that each got.

#274 docs: Add prerequisites to deployment guide
  docs/deploying.md
Labels: cla: yes

#273 fix: add proper build tag
  cloudbuild_update_images.yaml
Labels: cla: yes

#276 docs: Add a missing backslash in deploying.md
  docs/deploying.md
Labels: cla: yes

#283 refactor(pubsub): replace gob with msgpack
  go.mod
  go.sum
  internal/pkg/metadb/blobref/chunkref/chunkref.go
  internal/pkg/metadb/blobref/chunkref/chunkref_test.go
  internal/pkg/metadb/record/record.go
Labels: cla: yes

#284 docs: change alpha to beta in readme
  README.md
Labels: cla: yes

#278 docs: Tweaking steps for garbage collection
  deploy/datastore/index.yaml
  docs/deploying.md
Labels: cla: yes

#287 feat: remove opaque string limit check
  internal/app/server/open_saves.go
  internal/app/server/open_saves_test.go
Labels: enhancement, cla: yes

#288 fix: crash in CreateChunkedBlob with invalid param
  internal/app/server/open_saves.go
  internal/app/server/open_saves_test.go
Labels: bug, cla: yes
